[pytest]
base_url = https://the-internet.herokuapp.com
# norecursedirs tells pytest: "Do not even look inside these folders"
norecursedirs = sandbox .venv .git
# addopts sets the default behavior so you don't have to type it every time
addopts = -m "not infrastructure" --strict-markers
markers =
    infrastructure: Verification tests for framework/reporting (designed to fail)
    ui: General user interface tests

# Show logs in the terminal as they happen
log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)